react-native-menu/menu

.github/workflows/ci.yml
example/ios/Podfile.lock
ios/Menu-Bridging-Header.h
react-native-menu.podspec

Fixes podspec to use `React` instead of `React-Core`. This is required for projects using Swift until React Native 0.64
pod install runs without problem

fix: Podspec

---

README.md
android/build.gradle
android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManager.kt
example/src/App.tsx
ios/RCTAlertAction.swift
ios/RCTMenuItem.swift
src/UIMenuView.android.tsx
src/UIMenuView.ios.tsx
src/UIMenuView.tsx
src/index.tsx
src/types.ts

Hi, I implemented missing android menu configuration which includes attributes matching iOS behavior, android icon (can be any android drawable from app's or system resources) and *color props for action title (Android only) and action image/icon
- android action attributes (destructive, hidden, disabled)
- android action title color
- android action image and image color
- ios image color
- readme update with new props available
Closes #57

feat(#57): android missing action properties, ios image color

---

README.md
android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManager.kt
src/types.ts

Hi, I added prop for switching android menu anchor to parent view, whether it is anchored to right or left corner of parent view 
Closes #64 
Run Android example app and pass `isAnchoredToRight` prop with value set to `true`

feat(#64): isAnchoredToRight android value

---

README.md
android/src/main/java/com/reactnativemenu/MenuView.kt
example/src/App.tsx
ios/MenuView.swift
ios/RCTMenuItem.swift
src/index.tsx
src/types.ts

Hi, I added sub menus for Android `PopupMenu` and iOS `UIMenu`. On Android there can be 1 lvl of nested subactions, on iOS there is no limitation.
Closes #80 
Run example app. On Android root items with submenu will have a icon indicating that there are some subitems to show. On iOS items that contain sub menu are displayed the same as normal items

feat(#80): sub menus functionality

---

ios/ActionSheetView.swift

Currently, this library does not work on iPads running iOS 13 or lower. The `ActionSheet` presentation mode needs additional popover information to be presented on an iPad. This fix provides this support. 
Run the example application on an iPad simulator running iOS 13 or lower

fix(#105): Add ActionSheet support for iPad on OS versions less than 14

---

example/ios/Podfile
example/ios/Podfile.lock
example/package.json
example/yarn.lock
package.json
yarn.lock

I couldn't get the example test app to build with Xcode 12.5. Following the info / minimum changes at this link (https://github.com/facebook/react-native/issues/31179#issuecomment-830184757), I was able to get the test app to compile
Ran the iOS test app and it loaded.

Fix: iOS test app compiles with Xcode 12.5

---

README.md

The mentioned issue for v0.63 also exists on v0.64. 
I was sure my problem doesn't relate to that since I'm on v0.64, so I think it's worth indicating that it also exists for versions above 0.63 🙂

Update README to indicate issue exists on RN v0.63 and above

---

ios/ActionSheetView.swift
ios/MenuView.swift

Fixes: #139 
If I mount the Menu component with a set of actions (e.g. A, B, C) and then an event changes the set of actions to a subset (B, C) the action A is never removed because actions are only appended
To test, set up a component that starts with a list of actions and then removes some of those actions from the prop list

Clear menu actions when actions are set

---

android/src/main/java/com/reactnativemenu/MenuView.kt

Hi, this is fix for android compile errors related to type mismatch
Closes #146 
Closes #70 
The main problem was that some changes were introduced to ReadableMap & ReadableArray between RN version 0.64 & 0.63. In newer version, methods like `.getMap` are returning non-null values, when in older versions, these values were nullable.
**Solution:**
A few `.isNull` methods on ReadableMap/ReadableArray objects were added to code, together with `!= null` checks and some more `?.` 
Try that on example app (RN 0.64) as well as older versions of RN (e.g. 0.63)

fix(#146,#70): android type mismatch

---

README.md
android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManager.kt
example/src/App.tsx
ios/ActionSheetView.swift
ios/MenuView.swift
ios/RCTUIMenuManager.m
src/types.ts

Hi, regarding #90 , I added `shouldOpenOnLongPress` prop which changes whether menu should be opened after normal press or long press
Run example app and check behavior of `shouldOpenOnLongPress` prop
Closes #90

feat(#90): long press support

---

android/gradle.properties
example/metro.config.js
example/react-native.config.js

Fix Lint Error and Android Build

---

ios/ActionSheetView.swift

On iOS versions, the `ActionSheetView` that is used instead of the `UIMenu` has an issue.
If you don't set the title prop, without this fix, a title will be displayed blank. So the effective title is there, instead of being invisible. The UIAlertSheet's title parameter is optional, so there's no need to force fallback to `""`.
Before:
After:
I had no idea how to run the project standalone.. seems like either some linking went wrong or the structure is incorrect.
I tested it by modifying the pod directly in the Development Pods folder, testing on device and then applying those changes to the files directly. ~~It would be great if you could document how to actually build the project for future contributors.~~  -> nvm I'm dumb and missed the Contributing.md file...
Hope this can be accepted …

fix(iOS): action sheet empty title when property not defined

---

ios/ActionSheetView.swift

On iOS versions <= 13, the `ActionSheetView` that is used instead of the `UIMenu` has an issue where actions only fire the first time. This provides a fix for that.
Fixes #236 
I had no idea how to run the project standalone.. seems like either some linking went wrong or the structure is incorrect.
I tested it by modifying the pod directly in the Development Pods folder, testing on device and then applying those changes to the files directly. ~~It would be great if you could document how to actually build the project for future contributors.~~  -> nvm I'm dumb and missed the Contributing.md file...
Hope this can be accepted into the source so I won't have to patch the package myself anymore :)

fix(iOS): action sheet actions only fired first time

---

src/types.ts

React 18 removed the `children` prop from the `React.FC` type. This PR merges the `MenuComponentProps` with `PropsWithChildren` (to restore the behavior as of React 17)

fix(types): add children prop to MenuView typings

---

src/index.tsx
src/types.ts

Export the `NativeActionEvent` type, so users can type their `onPressAction` function.
`NativeActionEvent` can successfully be imported from `'@react-native-menu/menu'`.

feat: Export `NativeActionEvent` type

---

android/gradle.properties

Fixes #394 
Updated default kotlin version so build would pass in React Native 0.69+ without modifying settings on client side
Android build passes

Update Kotlin version

---

ios/MenuView.swift
ios/RCTMenuItem.swift
src/types.ts

I added the option to display submenus as inline for iOS, which separates the menu items with a divider.
This does not break any existing code, but adds the option to display existing submenus as inline for iOS. Android will continue to display as a submenu.

feat: add displayInline for submenus in iOS

---

android/build.gradle

Jfrog has sunset JCenter for a while now. Today it was offline for most of the day causing many build failures. This should fix any further issues.
Did a clean test build.

fix: remove jcenter() in favor of mavenCentral()

---

android/gradle/wrapper/gradle-wrapper.properties

hey maintainers, thanks for the great project.  
I noticed that the Gradle version is too old if the project hasn't reset default properties will cause a build error on Android. 
related: https://github.com/nandorojo/zeego/pull/27  
I saw that project's [default kotlin version](https://github.com/react-native-menu/menu/blob/4abccac4e8aebb8f90115a0727fcff034f762719/android/gradle.properties#L1) is `1.6.10`, so I think need to upgrade Gradle version to `7.4` is correct. 
check if the project build works on Android.

fix: upgrade gradle version

---

android/src/main/java/com/reactnativemenu/MenuView.kt

Android build would crash after upgrading to sdk 33 as indicated [in issue 488](https://github.com/react-native-menu/menu/issues/488) . These changes get rid of the errors and it builds correctly now.
Tried building with sdk 31 (which is what would work before the changes) and it still passes the build.

fix: android sdk 33 compatibility

---

android/src/main/java/com/reactnativemenu/MenuView.kt

The single-tap menu is slow to respond on Android, this is because `onSingleTapConfirmed` is used which delays calling until it's sure it's a single tap and not a double tap (not something this module ever cares about). Switching to `onSingleTapUp` causes the menu to open more quickly (and doesn't mess with the long press functionality either).
Have tested manually with both single and long press setups.

Increase responsiveness of single tap menu on Android

---

ios/MenuView.swift
ios/RCTUIMenuManager.m
src/types.ts

The current menu does not support dark mode for iOS and Android. I think dark mode is a good feature.
I add dark mode to iOS platform, I think it should be enabled on Android  but I am not familiar with Android.

Support darkMode for iOS platform

---

README.md
example/src/App.tsx
ios/ActionSheetView.swift
ios/MenuView.swift
ios/RCTUIMenuManager.m
src/types.ts

This improves on the PR (https://github.com/react-native-menu/menu/commit/a21c18258c7c2d16b261ef800e4186032e6de995) with `themeVariant` which aims to override the current theme using the string `'dark'` and `'light'` or to respect the current system theme if `undefined` value passed.
* Previously `darkMode` will result in UIMenu to fallback to the light theme if the value is not defined, not following the system theme.
The PR also adds theming support to iOS 13 ActionSheet.
The example app has been updated to include the variable `themeVariant` and changes the menu theme for iOS.
|    | iOS 16 | iOS 13 |
|--------|--------|--------|
| `'light'` | ![iOS 16 UIMenu Light Theme](https://github.com/react-native-menu/menu/assets/8110786/7027fac8-d4a4-4090-9b39-8980b2b936d2) | ![iOS 13 …

feat(iOS): Allow menu to override system theme

---

example/ios/Podfile.lock
ios/RCTMenuItem.swift

As of iOS 15, `discoverabilityTitle` is no longer displayed as the subtitle UIActions. Subtitles are not visible to iOS users of this package. This update brings them back.
WIP
Fixes: https://github.com/react-native-menu/menu/issues/536

Fix missing subtitles on iOS

---

android/src/main/java/com/reactnativemenu/MenuViewManager.kt

Fixes https://github.com/react-native-menu/menu/issues/736
Not sure why, but it seems like RN 0.74 (or newer Kotlin compiler) is more strict in terms of value reassignment. While in the past we were able to use direct property access on the `view` argument, it seems like now we have to use usual property setters.
The app compiles successfully.
**Note**: there's still work to be done for bringing bridgeless compatbility to this library's Android side (maybe iOS as well). Namely, the current way of sending events doesn't seem to work on bridgeless, see: https://github.com/reactwg/react-native-new-architecture/discussions/154#discussioncomment-9082416
Do you have any insight on what could be the culprit and how to fix this?

[android] fix: use hitSlop setter instead of property access for RN 0.74 compatibility

---

CONTRIBUTING.md
example/.gitignore
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
package.json

After #748 , I removed the `package.json` in the `example` folder, and refactored `react-native.config` and `metro.config` so that we can run the example app from the root of the repo. I didn't update the scripts and README, this PR does that.
`yarn android` works

fix: repo scripts launch test app

---

ios/NewArch/MenuView.mm

After enabling new architecture on a test app, iOS build fails.
Issue was also reported in #750 
Removing what seems to be unneeded code to fix the build error

fix: iOS build error on new architecture

---

android/src/main/java/com/reactnativemenu/MenuOnPressActionEvent.kt
android/src/main/java/com/reactnativemenu/MenuView.kt

This is an example of how you should use `EventDispatcher` rather than `RCTEventEmitter` for event dispatching on Android (both old and new architecture).
I haven't tested this yet.

[Android] Move to EventDispatcher instead of RCTEventEmitter

---

ios/Shared/RCTMenuItem.swift
src/types.ts

Support for preferredElementSize, which enables horizontal UIElements within a UIMenu

feat(iOS): preferredElementSize

---

ios/MenuViewManager.mm

The import was set incorrectly for `OLD_ARCH` which leads to project's failing build.
Build an iOS project with `OLD_ARCH`.

Change incorrect OLD_ARCH header import

---

android/build.gradle
android/gradle.properties

This PR bumps the `minSdkVersion` to `23`, following the bump made by the react native team in `react-native@0.74` ([see release notes](https://reactnative.dev/blog/2024/04/22/release-0.74#android-minimum-sdk-bump-android-60). 
Solved #802

eat: updated minSdkVersion to sdk version 23, inline with react-native's 0.74.0 minSdkVersion

---

README.md

Hello and thanks for this package! While working on another lib, I created a package that can "convert" declarative stuff (React) for imperative use. Maybe it'll be useful to others too.
The idea is that you can take components 
```
function WrappedButton({ title, onPress }: WrappedButtonProps) {
return <button onClick={onPress}>{title}</button>;
}
function DoubleWrappedButton(props: WrappedButtonProps) {
return <WrappedButton {...props} />;
}
it('works for single child element', () => {
const props = { title: 'one', onPress: jest.fn() };
const propsTwo = { title: 'two', onPress: jest.fn() };
expect(extractProps(<WrappedButton {...props} />)).toStrictEqual([props]);
expect(extractProps(<DoubleWrappedButton {...propsTwo} />)).toStrictEqual([
propsTwo,
]);
});
```
and get out the props you …

docs: document declarative way of use

---

ios/MenuViewManager.mm

The PR https://github.com/react-native-menu/menu/pull/807 broke the build for me on RN 0.74, latest Xcode / macOS.
Instead of just reverting it, I now check for both includes to see which one works, then use that.

fix: Fix `<react_native_menu/react_native_menu-Swift.h>` not found on old arch

---

ios/NewArch/MenuView.mm

It fails to make a build with react-native@0.74.1, newArchEnabled = true and useFrameworks = "static"
The error is as shown below
`Compiling @react-native-menu/menu Pods/react-native-menu » MenuViewManager.mm › Compiling @react-native-menu/menu Pods/react-native-menu » MenuView.mm`
```
❌  (node_modules/@react-native-menu/menu/ios/NewArch/MenuView.mm:2:9)
1 | #ifdef RCT_NEW_ARCH_ENABLED
> 2 | #import <react_native_menu-Swift.h>
|         ^ 'react_native_menu-Swift.h' file not found
3 | #import "MenuView.h"
4 | 
5 | #import <react/renderer/components/RNMenuViewSpec/ComponentDescriptors.h>
```
I am using @react-native-menu/menu@1.1.2
The same solution has been applied in https://github.com/react-native-menu/menu/pull/807 and should also fix …

Fix building on iOS on react-native@0.74.1 newArchEnabled and static frameworks

---

README.md

These changes don't appear to be required.
I created a new app with `npx create-expo-app`, [enabled the New Architecture](https://docs.expo.dev/guides/new-architecture/#enable-the-new-architecture-in-an-existing-project), installed `@react-native-menu/menu`, copied over the example from the README, then compiled and ran the project with `npx expo run:ios` - it worked as expected.

Remove the Fabric instructions from README

---

ios/MenuViewManager.mm
ios/Shared/MenuViewImplementation.swift
src/index.tsx
src/types.ts

Adds the `hitSlop` parameter to the menu component so that small buttons can still be pressed.
Contains @thomasttvo's changes from #627, updated for the latest version of the library.

Add hitSlop support (#627)

---

README.md
example/src/App.tsx
src/UIMenuView.tsx
src/types.ts

As also mentioned in https://github.com/react-native-menu/menu/issues/817, having a `testID` is quite useful for unit testing and automation purposes. This PR addresses that
Additionally, I spent some time trying mock the `MenuView` behaviour and couldn't find any example around. I'm adding an example here as it's a common use case and would be very useful for future users of this library.
Run: `yarn typescript` && `yarn prepare`

feat(props): adding test id and library mock example

---

android/src/main/java/com/reactnativemenu/MenuViewManager.kt

Upgrading React Native to 0.76 causes a build crash due to a change in the signature of setBorderColor in version 0.76 ([ReactViewGroup.java](https://github.com/facebook/react-native/blob/2e10ba945f6f2dca8d8cf1bb0db1d67fd50f2235/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java#L345)).
This PR introduced the new signature: https://github.com/facebook/react-native/commit/58c726a6bade42946cc28191de5f7ddb109d63f0
You can see the relevant diff here: https://github.com/facebook/react-native/commit/58c726a6bade42946cc28191de5f7ddb109d63f0#diff-0830ad3c2f92a395a52a1175e0868ce8c7f195ca2a95958e932077d00dd79021L308.
With this change, we no longer need to extract the RGB and alpha components; we can now directly pass the color.

fix: Remove custom logic for extracting RGB and alpha components for setBorderColor

---

android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManager.kt

This PR adds support for hit slop on the MenuView component for Android, improving touch responsiveness and user experience.
- Added `mHitSlopRect` property to store the hit slop rectangle
- Implemented `setHitSlopRect` method to update the hit slop and trigger touch delegate update
- Added `onSizeChanged` and `onAttachedToWindow` overrides to update touch delegate
- Implemented `updateTouchDelegate` method to apply hit slop and set touch delegate
Please test the following scenarios:
1. Menu opens correctly with default touch area
2. Menu opens correctly when hit slop is applied
3. Hit slop works as expected for all sides (left, top, right, bottom)
4. Touch delegate updates properly when view size changes or when attached to window
This implementation enhances the touch area of the …

fix(android): hit slop functionality

---

CONTRIBUTING.md
android/build.gradle
android/src/main/java/com/reactnativemenu/MenuViewManagerBase.kt
android/src/reactNativeVersionPatch/MenuViewManager/75/com/reactnativemenu/MenuViewManager.kt
android/src/reactNativeVersionPatch/MenuViewManager/latest/com/reactnativemenu/MenuViewManager.kt

The previous PR introduced a fix for React Native 0.76 compatibility but inadvertently broke support for earlier React Native versions https://github.com/react-native-menu/menu/pull/941. This PR restructures the Android implementation to support multiple versions of React Native by providing separate Kotlin class implementations based on the React Native version in use.
- **Version-Specific Implementations**: Added a new folder, `android/src/reactNativeVersionPatch`, to store version-specific implementations of classes, ensuring compatibility across different React Native versions.
- **Gradle Build Updates**: Updated `build.gradle` to import the files from `reactNativeVersionPatch`, streamlining the integration of version-dependent classes.
- **MenuViewManager Refactor**: Refactored …

Add Version-Specific Kotlin Implementations for Android to Support React Native 0.76+ and lower

---

README.md
android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManagerBase.kt
example/src/App.tsx
src/UIMenuView.android.tsx
src/index.tsx
src/types.ts

- Added a new `show()` method to programmatically display menus on Android
- Implemented ref forwarding to expose the `show()` method to React Native components
- Added TypeScript types to support the new functionality
- Updated example app to demonstrate the new feature
- Added native Android command handling in `MenuViewManagerBase.kt`
- Created a new `MenuComponentRef` type for TypeScript support
- Wrapped the native component with ref forwarding in `UIMenuView.android.tsx`
- Added example usage with a button trigger in the example app
~~~typescript
const menuRef = useRef<MenuComponentRef>(null);
// Show menu programmatically
menuRef.current?.show();
// In JSX
<MenuView
ref={menuRef}
title="Menu Title"
actions={...}
/>
~~~
- Verified menu display using the example app
- Confirmed …

feat(android): add show method to MenuView component

---

ios/NewArch/FabricViewImplementationProtocol.swift
ios/NewArch/MenuView.mm
ios/Shared/ActionSheetView.swift
ios/Shared/MenuViewImplementation.swift
src/NativeModuleSpecs/UIMenuNativeComponent.ts

When using the new Architecture in iOS some of the props like `themeVariant`, `shouldOpenOnLongPress` and `hitSlop` are not handled correctly.
| Before      | After      |
| ------------- | ------------- |
|<img width="1512" alt="Screenshot 2024-12-01 at 14 05 20" src="https://github.com/user-attachments/assets/897595f0-bc41-4757-90a2-860f8b59a0a2">| <img width="1512" alt="Screenshot 2024-12-01 at 14 07 49" src="https://github.com/user-attachments/assets/4f102fac-d6f7-4387-ab2f-ebf830bd340d">|
- validated that all props are passed correctly when using the new architecture.

fix(iOS): new architecture props

---

android/src/main/java/com/reactnativemenu/MenuView.kt

When trying to compile our app with the new RN 0.77 we ran into the following error:
> Task :react-native-menu_menu:compileDebugKotlin FAILED
e: file:///.../@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt:60:3 'onTouchEvent' overrides nothing. e: file:///.../@react-native-menu/menu/android/src/main/java/com/reactnativemenu/MenuView.kt:61:35 Argument type mismatch: actual type is 'android.view.MotionEvent?', but 'android.view.MotionEvent' was expected.
Compiling on RN 0.77 should work

fix(android): package was failing to compile on RN 0.77

---

README.md
plugin/withAndroidDrawables.js

Inspirited by [this tweet](https://x.com/iamarunabh/status/1916462096667050154) claiming it was easy to add custom icons for Android menu items, I spent longer than I hoped figuring it out 😅 
This PR adds my findings, in the hopes that it saves other people some time.
No code changes, just view the docs. the added expo config plugin is not automatically shipped or installed with this library, but can be manually copied by people reading the README.md section added in this PR.

Add documentation on custom icons for Android

---

package.json

Newer react native versions require the `componentProvider` in codegen, so this pr adds it to resolve the crash
closes #1068
Tested it with a new react native project 0.80.1

fix: fix ios crash by declaring component provider

---

.tool-versions
plugin/withAndroidDrawables.js

fix: lint error
