example/src/App.tsx
tsconfig.json

Fix package name in example
Example project working without problem

chore: fix example package name

---

src/UIMenuView.tsx
yarn.lock

Added children for unimplemented view so the visuals would be the same for unimplemented platforms

chore: add children for unimplemented view

---

package.json
src/UIMenuView.ios.tsx
yarn.lock

updated prettier and applied prettier

chore: update prettier

---

README.md
src/types.ts

add android screenshot to README, and add platform specification to type docs
only document changes

docs: update type docs and screenshot

---

android/src/main/java/com/reactnativemenu/MenuView.kt

resolves #60 
Added safe call for arguments that may not exist
Build pass on android

Fix: build error on android

---

android/src/main/java/com/reactnativemenu/MenuView.kt

fix: android build

---

src/types.ts

fix missing import type

---

.github/workflows/ci.yml

Update node version running in CI

Update node version running in CI

---

.github/workflows/ci.yml

Fix CI runner

---

README.md

Hello and thanks for the package.
I updated `shouldOpenOnLongPress` to false because when I copied the example the other day, it took me some time to understand why tapping the button does not show the menu :D.
I also added a note about theming.

docs: update example and theming docs

---

.github/workflows/ci.yml

Add node v20 to ci

---

android/build.gradle

See: https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1597386954
N/A

RN 0.73 compatibility for Android

---

ios/Shared/RCTMenuItem.swift

Add support that images contained on xcassets images

---

babel.config.js
example/android/gradle/wrapper/gradle-wrapper.properties
example/babel.config.js
example/package.json
example/yarn.lock
package.json
yarn.lock

Needed for proper New Architecture support, see: https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#babel-package-renames
Upgraded example app to RN 0.73 with newArch enabled:

replace metro-react-native-babel-preset with @react-native/babel-preset

---

.github/workflows/ci.yml
.tool-versions

fix: android ci

---

ios/Shared/RCTMenuItem.swift
src/types.ts

Support for keepsMenuPresented

feat(iOS): keepsMenuPresented

---

README.md

Add to README support for iOS image resources

---

CONTRIBUTING.md
README.md
react-native.config.js
src/types.ts
src/utils.ts

There are some minor typos and ESLint issues, which are failing CI, this PR fixes them.

Fix ESLint issues, minor typos correction

---

android/src/main/java/com/reactnativemenu/MenuView.kt

if prop value for state is "on" or "off" then isCheckable = true and isChecked = menuState, otherwise isCheckable = false

add isCheckable from state prop

---

package.json

fix: remove unused part of script

---

android/src/main/java/com/reactnativemenu/MenuView.kt
android/src/main/java/com/reactnativemenu/MenuViewManagerBase.kt

@Naturalclar 
RN 0.77 is a bit more strict in terms of nullability. This requires to adjust the nullability of certain variables in the codebase.
I've tested the changes in my own app running both RN 0.77 and RN 0.76 and it works fine for me.

fix compilation on RN 0.77

---

android/src/main/java/com/reactnativemenu/MenuViewManagerBase.kt

@Naturalclar 
Implements the fix from https://github.com/react-native-menu/menu/issues/1041#issuecomment-2703464209
Build the app

fix android build issue on 0.78
